sudo: required

language: c++

services:
    - docker
env:
  matrix:
    - CC_BUILD=gcc-6
      CXX_BUILD=g++-6
      OPENMP=ON
      OPENCL=OFF

    - CC_BUILD=clang-3.9
      CXX_BUILD=clang++-3.9
      OPENMP=OFF
      OPENCL=OFF

before_install:
    - docker build -t trisycl .
    - docker ps -a
    - docker images

script:
    - docker run -e COMPILER=${CXX_BUILD} -e C_COMPILER=${CC_BUILD} -e OPENMP=${OPENMP} -e OPENCL=${OPENCL} trisycl
