name: CMake

on:
  # Triggers the workflow on push, PR or manual dispatch
  push:
    branches:
    # Also launch the CI when creating a tag
    tags:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  build-and-test:

    name: Run the validation inside Docker with specific OS and options

    # By latest GitHub means actually latest LTS only
    runs-on: ubuntu-latest

    # Run into an even more recent Ubuntu inside Docker to have recent
    # compilers and C++ standard library
    container:
      # Ubuntu 23.04
      image: docker://ubuntu:lunar

    strategy:
      # Run all the test even if there are some which fail
      fail-fast: false

      matrix:
       include:
         - c_compiler: gcc-12
           cxx_compiler: g++-12
           OpenMP: ON
           OpenCL: OFF

         - c_compiler: gcc-12
           cxx_compiler: g++-12
           OpenMP: ON
           OpenCL: ON

         - c_compiler: clang-17
           cxx_compiler: clang++-17
           OpenMP: ON
           OpenCL: OFF

         - c_compiler: clang-17
           cxx_compiler: clang++-17
           OpenMP: ON
           OpenCL: ON

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          apt-get update
          apt-get install -y build-essential cmake g++ git \
            libboost-all-dev libgtkmm-3.0-dev librange-v3-dev \
            pkgconf

      - name: Declare LLVM package repository if needed
        if: ${{ startsWith(matrix.c_compiler, 'clang') || startsWith(matrix.cxx_compiler, 'clang') }}
        shell: bash
        run: |
          apt-get install -y wget
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
          # "Parse" the Linux distribution parameters
          source /etc/os-release
          echo "deb http://apt.llvm.org/$VERSION_CODENAME llvm-toolchain-$VERSION_CODENAME main" \
            > /etc/apt/sources.list.d/llvm.list
          echo "deb-src http://apt.llvm.org/$VERSION_CODENAME llvm-toolchain-$VERSION_CODENAME main" \
            >> /etc/apt/sources.list.d/llvm.list
          apt-get update

      - name: Install the C compiler
        run: apt-get install -y ${{matrix.c_compiler}}

      - name: Install the C++ compiler
        # Do not install the C++ compiler if it is clang++ since it comes
        # along the Clang C compiler
        if: ${{ !startsWith(matrix.cxx_compiler, 'clang') }}
        run: apt-get install -y ${{matrix.cxx_compiler}}

      - name: Install OpenMP support if needed
        # Clang requires a specific OpenMP library to run
        if: ${{ matrix.OpenMP == 'ON' && startsWith(matrix.cxx_compiler, 'clang') }}
        shell: bash
        run: |
          # Get the clang++ version, which is what is left when we remove "clang++-"
          CXX_COMPILER=${{matrix.cxx_compiler}}
          cxx_compiler_version=${CXX_COMPILER#clang++-}
          apt-get install -y libomp-${cxx_compiler_version}-dev

      - name: Install OpenCL with POCL if needed
        if: ${{ matrix.OpenCL == 'ON' }}
        run: apt-get install -y opencl-headers ocl-icd-opencl-dev libpocl-dev

      # Use ccache to speed-up compilation to also fit into GitHub Actions
      # resource limitations https://github.com/hendrikmuhs/ccache-action
      - name: install-ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "1G"

      - name: Configure CMake for ${{matrix.c_compiler}}, ${{matrix.cxx_compiler}},
          OpenMP=${{matrix.OpenMP}}, OpenCL=${{matrix.OpenCL}}
        # Create the build directory in ${{github.workspace}}/build
        # and inject ccache in the build system
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DTRISYCL_OPENCL=${{matrix.OpenCL}} -DTRISYCL_OPENMP=${{matrix.OpenMP}}
          -DCMAKE_C_COMPILER=${{matrix.c_compiler}} -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}}
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build for ${{matrix.c_compiler}}, ${{matrix.cxx_compiler}},
          OpenMP=${{matrix.OpenMP}}, OpenCL=${{matrix.OpenCL}}
        # Compile all the tests using all the available cores
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          --verbose --parallel `nproc`

      - name: Test for ${{matrix.c_compiler}}, ${{matrix.cxx_compiler}},
          OpenMP=${{matrix.OpenMP}}, OpenCL=${{matrix.OpenCL}}
        # Run the tests which do not use the GUI since there is no
        # display or user
        run: ctest --label-exclude GUI --test-dir ${{github.workspace}}/build --build-config ${{env.BUILD_TYPE}}
